state_caps_deck = Deck.create!(name: "U.S. State Capitals")
Card.create!(question: "What is the capital of Alabama?", answer: "Montgomery", deck: state_caps_deck)
Card.create!(question: "What is the capital of Illinois?", answer: "Springfield", deck: state_caps_deck)
Card.create!(question: "What is the capital of California?", answer: "Sacramento", deck: state_caps_deck)
Card.create!(question: "What is the capital of Texas?", answer: "Austin", deck: state_caps_deck)
Card.create!(question: "What is the capital of New York?", answer: "Albany", deck: state_caps_deck)

albums = Deck.create!(name: "Albums and Musicians")
Card.create!(question: "Which artist made the album 'Thriller'?", answer: "Michael Jackson", deck: albums)
Card.create!(question: "Which artist made the album 'Rubber Soul'?", answer: "The Beatles", deck: albums)
Card.create!(question: "Which artist made the album 'Rumours'?", answer: "Fleetwood Mac", deck: albums)
Card.create!(question: "Which artist made the album 'Dark Side of the Moon'?", answer: "Pink Floyd", deck: albums)
Card.create!(question: "Which artist made the album 'Yeezus'?", answer: "Kanye West", deck: albums)

hockey = Deck.create!(name: "Hockey Teams and Cities")
Card.create!(question: "Which NHL team plays in the city of Los Angeles?", answer: "The Kings", deck: hockey)
Card.create!(question: "Which NHL team plays in the city of Chicago?", answer: "The Blackhawks", deck: hockey)
Card.create!(question: "Which NHL team plays in the city of New York City?", answer: "The Rangers", deck: hockey)
Card.create!(question: "Which NHL team plays in the city of Montreal?", answer: "The Canadians", deck: hockey)
Card.create!(question: "Which NHL team plays in the city of Dallas?", answer: "The Stars", deck: hockey)

world = Deck.create!(name: "World Capitals")
Card.create!(question: "What is the capital of Germany?", answer: "Berlin", deck: world)
Card.create!(question: "What is the capital of South Korea?", answer: "Seoul", deck: world)
Card.create!(question: "What is the capital of Venezuela?", answer: "Caracas", deck: world)
Card.create!(question: "What is the capital of Egypt?", answer: "Cairo", deck: world)
Card.create!(question: "What is the capital of Australia?", answer: "Canberra", deck: world)

directors = Deck.create!(name: "Movies and Directors")
Card.create!(question: "Who directed the movie 'Breathless'?", answer: "Jean Luc Godard", deck: directors)
Card.create!(question: "Who directed the movie 'Dazed and Confused'?", answer: "Richard Linklater", deck: directors)
Card.create!(question: "Who directed the movie 'Citizen Kane'?", answer: "Orson Welles", deck: directors)
Card.create!(question: "Who directed the movie 'The Breakfast Club'?", answer: "John Hughes", deck: directors)
Card.create!(question: "Who directed the movie 'Taxi Driver'?", answer: "Martin Scorcese", deck: directors)

greetings = Deck.create!(name: "Greetings in Other Languages")
Card.create!(question: "In which language do you greet someone with, 'Hola'?", answer: "Spanish", deck: greetings)
Card.create!(question: "In which language do you greet someone with, 'Xin chào'?", answer: "Vietnamese", deck: greetings)
Card.create!(question: "In which language do you greet someone with, 'Bonjour'?", answer: "French", deck: greetings)
Card.create!(question: "In which language do you greet someone with, 'Merhaba'?", answer: "Turkish", deck: greetings)
Card.create!(question: "In which language do you greet someone with, 'Hej'?", answer: "Danish", deck: greetings)


User.create!(name: "Gabi Voicu", email: "gabi@dbc.com", password: "1234")
User.create!(name: "Jane Kim", email: "jane@dbc.com", password: "1234")
User.create!(name: "Matt Gray", email: "matt@dbc.com", password: "1234")
